version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - scd-network

  backend:
    image: sodapopin/scd-project-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
      - JWT_SECRET=abc123456789
    depends_on:
      - mongodb
    networks:
      - scd-network

  frontend:
    image: sodapopin/scd-project-frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - scd-network

networks:
  scd-network:
    driver: bridge

volumes:
  mongodb_data:
