name: Build and Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # ...existing code for checkout and docker setup...

      - name: Setup Minikube Certificate
        run: |
          $certPath = "$env:USERPROFILE\.minikube\ca.crt"
          kubectl config set-cluster minikube --embed-certs --certificate-authority=$certPath
          kubectl config use-context minikube
        shell: powershell

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/deployment.yaml --validate=false
          kubectl apply -f kubernetes/service.yaml --validate=false
        shell: powershell
        
      - name: Wait for deployments
        run: |
          kubectl wait --for=condition=available deployment/backend -n scd-project --timeout=300s
          kubectl wait --for=condition=available deployment/frontend -n scd-project --timeout=300s
          kubectl get all -n scd-project
        shell: powershell
