name: Build and Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # ...existing code for checkout and docker setup...

      - name: Setup Minikube Certificate
        run: |
          # Wait for Minikube to be ready
          $retryCount = 0
          do {
            $status = minikube status --format '{{.Host}}' 2>&1
            if ($status -eq 'Running') { break }
            Start-Sleep -Seconds 5
            $retryCount++
          } while ($retryCount -lt 12)  # 1 minute timeout

          # Setup certificates
          $certPath = "$env:USERPROFILE\.minikube\ca.crt"
          kubectl config set-cluster minikube --embed-certs --certificate-authority=$certPath
          kubectl config use-context minikube

          # Verify connection
          kubectl cluster-info
          if (-not $?) { throw "Failed to connect to cluster" }
        shell: powershell

      - name: Create namespace
        run: |
          kubectl create namespace scd-project --dry-run=client -o yaml | kubectl apply -f -
        shell: powershell

      - name: Deploy to Minikube
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
        shell: powershell
        
      - name: Wait for deployments
        run: |
          kubectl wait --for=condition=available deployment/backend -n scd-project --timeout=300s
          kubectl wait --for=condition=available deployment/frontend -n scd-project --timeout=300s
          kubectl get all -n scd-project
        shell: powershell
