name: Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-to-minikube: # Changed job name for clarity
    runs-on: self-hosted # IMPORTANT: Assumes Minikube is running and accessible on this runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # This step is kept to access the Kubernetes manifest files (e.g., in the 'kubernetes/' directory)

      # Step to verify Minikube is running and its context is set.
      - name: Verify Minikube status and set context
        shell: cmd # Assuming a Windows runner
        run: |
          echo "Checking Minikube status..."
          minikube status
          echo "Updating kubeconfig context for Minikube..."
          minikube update-context
          echo "Minikube context should now be set for kubectl."

      - name: Deploy to Minikube
        shell: cmd # Using cmd shell as in the original file
        run: |
          REM Use 'minikube kubectl --' to ensure commands are correctly routed to the Minikube cluster.
          REM Add '--insecure-skip-tls-verify=true' to bypass TLS certificate verification for Minikube.

          REM Create namespace if it doesn't exist. Ignore error if it already exists.
          minikube kubectl -- --insecure-skip-tls-verify=true create namespace scd-project || echo "Namespace scd-project may already exist or an error occurred. Continuing..."

          REM Apply all Kubernetes manifest files from the 'kubernetes' directory to the specified namespace.
          REM Ensure your Kubernetes manifests are configured to pull the correct image tags 
          REM (e.g., sodapopin/scd-project-backend:latest, sodapopin/scd-project-frontend:latest)
          minikube kubectl -- --insecure-skip-tls-verify=true apply -f kubernetes/ -n scd-project

          REM Wait for the backend deployment to complete its rollout.
          minikube kubectl -- --insecure-skip-tls-verify=true rollout status deployment/backend -n scd-project --timeout=5m

          REM Wait for the frontend deployment to complete its rollout.
          minikube kubectl -- --insecure-skip-tls-verify=true rollout status deployment/frontend -n scd-project --timeout=5m
          
          echo "Deployments rollout status checked."
