name: Deploy to Minikube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-to-minikube: # Changed job name for clarity
    runs-on: self-hosted # IMPORTANT: Assumes Minikube is running and accessible on this runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # This step is kept to access the Kubernetes manifest files (e.g., in the 'kubernetes/' directory)

      # Step to verify Minikube is running and its context is set.
      - name: Verify Minikube status and set context
        shell: cmd # Assuming a Windows runner
        run: |
          echo "Checking Minikube status..."
          minikube status
          echo "Updating kubeconfig context for Minikube..."
          minikube update-context
          echo "Minikube context should now be set for kubectl."

      - name: Deploy to Minikube
        shell: cmd # Using cmd shell as in the original file
        run: |
          # Get and use Minikube's kubeconfig
          $env:KUBECONFIG="$env:USERPROFILE\.kube\config"
          minikube kubectl -- config view --flatten > $env:KUBECONFIG
    
          # Create namespace (skip if exists)
          minikube kubectl -- create namespace scd-project --dry-run=client -o yaml | minikube kubectl -- apply -f -
    
          # Apply manifests with validation disabled
          minikube kubectl -- apply -f kubernetes/ -n scd-project --validate=false
    
          # Check deployments
          minikube kubectl -- rollout status deployment/backend -n scd-project --timeout=5m
          minikube kubectl -- rollout status deployment/frontend -n scdn-project --timeout=5m
