name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker to use Minikube's environment
      run: minikube docker-env | Invoke-Expression
      shell: powershell

    - name: Get Minikube IP
      id: minikube_ip
      run: |
        $ip = minikube ip
        echo "MINIKUBE_IP=$ip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell

    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t sodapopin/scd-project-backend:latest .

    - name: Build Frontend Docker image
      run: |
        cd frontend
        echo "VITE_API_URL=http://${{ env.MINIKUBE_IP }}:5000" > .env
        docker build -t sodapopin/scd-project-frontend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Backend Docker image
      run: docker push sodapopin/scd-project-backend:latest

    - name: Push Frontend Docker image
      run: docker push sodapopin/scd-project-frontend:latest

    - name: Create namespace
      run: |
        kubectl create namespace scd-project --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Minikube
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
        
    - name: Wait for deployments
      run: |
        kubectl rollout status deployment/backend -n scd-project
        kubectl rollout status deployment/frontend -n scd-project
        kubectl get all -n scd-project
